import {
  createContext,
  useContext,
  useState,
  useCallback,
  useEffect,
} from "react";
import AsyncStorage from "@react-native-async-storage/async-storage";

const STORAGE_KEY = "app_language";

const STRINGS = {
  EN: {
    jai: "TripKart",
    appName: "Monthly Yatra Parivar",
    quickAccess: "Quick Access",
    bookBus: "Book Bus",
    bookBusSub: "Book a seat",
    membership: "Membership",
    membershipSub: "Join Parivar",
    donate: "Donate",
    donateSub: "Support seva",
    contact: "Contact",
    contactSub: "Get in touch",
    monthlyYatra: "· TripKart ·",
    bannerTitle: "Plan Your\nSacred Journey",
    bannerSub: "AC & Non-AC buses · Trusted operators · Easy seat booking",
    exploreToursBtn: "Explore Tours",
    bookingOpen: "Booking open",
    yatrasReady: "upcoming yatra ready for darshan",
    upcomingYatras: "Upcoming Tours",
    upcomingYatrasSub: "Plan your next tour",
    viewAll: "View All →",
    noUpcomingYatras: "No upcoming tours at the moment",
    devotionalServices: "Devotional Services",
    devotionalServicesSub: "Spiritual offerings",
    dailyAarti: "Daily Aarti",
    readChalisa: "Read Chalisa",
    devotionalBhajans: "Devotional Bhajans",
    devoteesVoice: "Devotees' Voice",
    devoteesVoiceSub: "Blessed experiences",
    mantra: "Your Journey, Our Promise",
    mantraEn: "Seamless Tours · Sacred Destinations",
    home: "Home",
    tours: "Tours",
    bookings: "Bookings",
    profile: "Profile",
    devotion: "Devotion",
    loading: "Loading...",
    back: "Back",
    save: "Save",
    cancel: "Cancel",
    delete: "Delete",
    edit: "Edit",
    confirm: "Confirm",
    error: "Error",
    success: "Success",
    refresh: "Refresh",
    submit: "Submit",
    close: "Close",
    login: "Login",
    logout: "Logout",
    register: "Register",
    bookNow: "Book Now",
    upcoming: "Upcoming Tours",
    noTours: "No tours available",
    seatsLeft: "seats left",
    perSeat: "Per seat",
    duration: "Duration",
    aboutYatra: "About this tour",
    whatsIncluded: "What's included",
    itinerary: "Itinerary",
    myBookings: "My Bookings",
    noBookings: "No bookings yet",
    confirmBooking: "Confirm Booking",
    bookingConfirmed: "Booking Confirmed",
    editProfile: "Edit Profile",
    changePassword: "Change Password",
    adminPanel: "Admin Panel",
    logoutConfirm: "Are you sure you want to logout?",
    memberSince: "Member since",
    personalDetails: "Personal Details",
    travelDetails: "Travel Details",
    reviewPay: "Review & Pay",
    fullName: "Full Name",
    mobile: "Mobile Number",
    emailOpt: "Email (optional)",
    address: "Address",
    age: "Age",
    fatherName: "Father / Husband Name",
    gender: "Gender",
    aadhar: "Aadhar Number",
    vrat: "Observing Vrat?",
    vatHint: "Will you fast during the tour?",
    noOfSeats: "Number of Seats",
    boardingPoint: "Boarding Point",
    totalAmount: "Total Amount",
    continueBtn: "Continue",
    confirmPay: "Confirm & Pay",
    additionalPassengers: "Additional Passengers",
    passengerNum: "Passenger",
    gallery: "Gallery",
    photos: "Photos",
    videos: "Videos",
    bhajans: "Bhajans",
    chalisa: "Chalisa",
    aarti: "Aarti",
    dashboard: "Dashboard",
    users: "Users",
    members: "Members",
    enquiries: "Enquiries",
    feedback: "Feedback",
    donations: "Donations",
    settings: "Settings",
    noResults: "No results found",
    tryAgain: "Try again",
    contactUs: "Contact Us",
    about: "About Us",
    myBookingsSub: "Your journeys",
    loginToViewBookings: "Login to view your bookings",
    loginRegister: "Login / Register",
    noBookingYet: "No bookings yet",
    sacredJourneyAwaits: "Your sacred journey awaits",
    exploreYatras: "Explore Tours",
    viewTicket: "View Ticket",
    welcomeBack: "Welcome Back",
    welcomeBackSub: "Glad to see you, devotee",
    joinUs: "Join Us",
    joinUsSub: "Welcome to Shyam Parivar",
    resetPwd: "Reset Password",
    resetPwdSub: "We will send a reset link to your email",
    marriageAidSub: "Marriage assistance",
    aartiSub: "Daily Aarti",
    chalisaSub: "Khatu Shyam Chalisa",
    donationSuccessTitle: "Donation Successful",
    donationSuccessMsg: "Jai Shree Shyam! Your donation has been received.",
    donateHeroSub: "Every service is by Shyam Ji's grace.",
    anonymousDonate: "Make this donation anonymous",
    gallerySub: "Memories & Darshan",
    aboutHeroSub: "TripKart Parivar",
    aboutMissionDesc:
      "TripKart Parivar is a spiritual family dedicated to the service of Khatu Shyam Ji and the community. We organize monthly tours, devotional events, and social services to bring devotees together and spread the message of love, faith, and compassion.",
    membershipHeroSub: "Become part of the Parivar",
    membershipSuccessSub:
      "Your application has been submitted successfully.\nWe will review and contact you shortly.",
    devotionHeaderSub: "Bhakti · Music · Aarti",
    bhajanChipSub: "Songs",
    aartiChipSub: "Prayer",
    chalisaChipSub: "Hymn",
    kirtanChipSub: "Chorus",
    feedbackNote: "Jai Shree Shyam · Your feedback helps us serve better",
  },

  HI: {
    jai: "जय श्री श्याम",
    appName: "श्याम सवारिया परिवार",
    quickAccess: "त्वरित पहुँच",
    bookBus: "बस बुक करें",
    bookBusSub: "सीट बुक करे",
    membership: "सदस्यता",
    membershipSub: "सदस्य बने",
    donate: "दान करें",
    donateSub: "सेवा में दान",
    contact: "संपर्क",
    contactSub: "संपर्क करें",
    monthlyYatra: "· ट्रिपकार्ट ·",
    bannerTitle: "पवित्र यात्रा\nकी योजना बनाएं",
    bannerSub: "AC व Non-AC बसें · विश्वसनीय संचालक · आसान सीट बुकिंग",
    exploreToursBtn: "यात्राएं देखें",
    bookingOpen: "बुकिंग खुली है",
    yatrasReady: "आगामी यात्रा दर्शन के लिए तैयार",
    upcomingYatras: "आगामी यात्राएं",
    upcomingYatrasSub: "अगली यात्रा की योजना बनाएं",
    viewAll: "सभी देखें →",
    noUpcomingYatras: "इस समय कोई आगामी यात्रा नहीं",
    devotionalServices: "भक्ति सेवाएं",
    devotionalServicesSub: "आध्यात्मिक सेवाएं",
    dailyAarti: "श्याम जी आरती",
    readChalisa: "खाटू चालीसा",
    devotionalBhajans: "भजन व कीर्तन",
    devoteesVoice: "श्रद्धालु प्रतिक्रिया",
    devoteesVoiceSub: "भक्तों के अनुभव",
    mantra: "आपकी यात्रा, हमारा वादा",
    mantraEn: "सहज यात्रा · पवित्र मंजिलें",
    home: "होम",
    tours: "यात्राएं",
    bookings: "बुकिंग",
    profile: "प्रोफाइल",
    devotion: "भक्ति",
    loading: "लोड हो रहा है...",
    back: "वापस",
    save: "सहेजें",
    cancel: "रद्द करें",
    delete: "हटाएं",
    edit: "बदलें",
    confirm: "पुष्टि करें",
    error: "गलती",
    success: "सफलता",
    refresh: "रीफ्रेश",
    submit: "जमा करें",
    close: "बंद करें",
    login: "लॉगिन",
    logout: "लॉगआउट",
    register: "पंजीकरण",
    bookNow: "अभी बुक करें",
    upcoming: "आगामी यात्राएं",
    noTours: "कोई यात्रा उपलब्ध नहीं",
    seatsLeft: "सीटें बची",
    perSeat: "प्रति सीट",
    duration: "अवधि",
    aboutYatra: "इस यात्रा के बारे में",
    whatsIncluded: "क्या शामिल है",
    itinerary: "कार्यक्रम",
    myBookings: "मेरी बुकिंग",
    noBookings: "अभी तक कोई बुकिंग नहीं",
    confirmBooking: "बुकिंग पुष्टि करें",
    bookingConfirmed: "बुकिंग पुष्ट",
    editProfile: "प्रोफाइल संपादित करें",
    changePassword: "पासवर्ड बदलें",
    adminPanel: "एडमिन पैनल",
    logoutConfirm: "क्या आप लॉगआउट करना चाहते हैं?",
    memberSince: "सदस्य बने",
    personalDetails: "व्यक्तिगत विवरण",
    travelDetails: "यात्रा विवरण",
    reviewPay: "समीक्षा करें",
    fullName: "पूरा नाम",
    mobile: "मोबाइल नंबर",
    emailOpt: "ईमेल (वैकल्पिक)",
    address: "पता",
    age: "आयु",
    fatherName: "पिता / पति का नाम",
    gender: "लिंग",
    aadhar: "आधार संख्या",
    vrat: "व्रत रखेंगे?",
    vatHint: "क्या आप यात्रा के दौरान उपवास रखेंगे?",
    noOfSeats: "सीटों की संख्या",
    boardingPoint: "चढ़ने का स्थान",
    totalAmount: "कुल राशि",
    continueBtn: "जारी रखें",
    confirmPay: "पुष्टि करें और भुगतान करें",
    additionalPassengers: "अतिरिक्त यात्री",
    passengerNum: "यात्री",
    gallery: "गैलरी",
    photos: "फोटो",
    videos: "वीडियो",
    bhajans: "भजन",
    chalisa: "चालीसा",
    aarti: "आरती",
    dashboard: "डैशबोर्ड",
    users: "उपयोगकर्ता",
    members: "सदस्य",
    enquiries: "पूछताछ",
    feedback: "प्रतिक्रिया",
    donations: "दान",
    settings: "सेटिंग",
    noResults: "कोई परिणाम नहीं",
    tryAgain: "पुनः प्रयास",
    contactUs: "संपर्क करें",
    about: "हमारे बारे में",
    myBookingsSub: "आपकी यात्राएं",
    loginToViewBookings: "अपनी यात्राएं देखने के लिए लॉगिन करें",
    loginRegister: "लॉगिन / पंजीकरण",
    noBookingYet: "अभी तक कोई बुकिंग नहीं",
    sacredJourneyAwaits: "आपकी पावन यात्रा आपका इंतजार कर रही है",
    exploreYatras: "यात्राएं देखें",
    viewTicket: "टिकट देखें",
    welcomeBack: "पुनः स्वागत",
    welcomeBackSub: "पुनः स्वागत है, भक्त",
    joinUs: "जुड़ें",
    joinUsSub: "श्याम परिवार में आपका स्वागत है",
    resetPwd: "पासवर्ड रीसेट",
    resetPwdSub: "हम आपके ईमेल पर रीसेट लिंक भेजेंगे",
    marriageAidSub: "विवाह सहायता",
    aartiSub: "श्याम जी की आरती",
    chalisaSub: "खाटू श्याम चालीसा",
    donationSuccessTitle: "दान सफल",
    donationSuccessMsg: "जय श्री श्याम! आपका दान प्राप्त हो गया।",
    donateHeroSub: "हर सेवा, श्याम जी की कृपा।",
    anonymousDonate: "गुप्त दान करें",
    gallerySub: "दर्शन और स्मृतियाँ",
    aboutHeroSub: "श्याम सावरिया परिवार",
    aboutMissionDesc:
      "श्याम सावरिया परिवार एक आध्यात्मिक परिवार है, जो खाटू श्याम जी और समाज की सेवा के लिए समर्पित है। हम हर महीने यात्रा, भक्ति कार्यक्रम और सामाजिक सेवाएं आयोजित करते हैं।",
    membershipHeroSub: "श्याम परिवार का हिस्सा बनें",
    membershipSuccessSub:
      "आपका आवेदन सफलतापूर्वक जमा हो गया।\nहम जल्द ही आपसे संपर्क करेंगे।",
    devotionHeaderSub: "भक्ति · संगीत · आरती",
    bhajanChipSub: "भजन",
    aartiChipSub: "आरती",
    chalisaChipSub: "चालीसा",
    kirtanChipSub: "कीर्तन",
    feedbackNote: "जय श्री श्याम · आपकी प्रतिक्रिया हमारी सेवा बेहतर बनाती है",
  },

  PA: {
    jai: "ਜੈ ਸ਼੍ਰੀ ਸ਼ਿਆਮ",
    appName: "ਮਾਸਿਕ ਯਾਤਰਾ ਪਰਿਵਾਰ",
    quickAccess: "ਤੁਰੰਤ ਪਹੁੰਚ",
    bookBus: "ਬੱਸ ਬੁੱਕ ਕਰੋ",
    bookBusSub: "ਸੀਟ ਬੁੱਕ ਕਰੋ",
    membership: "ਮੈਂਬਰਸ਼ਿਪ",
    membershipSub: "ਪਰਿਵਾਰ ਨਾਲ ਜੁੜੋ",
    donate: "ਦਾਨ ਕਰੋ",
    donateSub: "ਸੇਵਾ ਵਿੱਚ ਦਾਨ",
    contact: "ਸੰਪਰਕ",
    contactSub: "ਸੰਪਰਕ ਕਰੋ",
    monthlyYatra: "· ਟ੍ਰਿਪਕਾਰਟ ·",
    bannerTitle: "ਆਪਣੀ ਪਵਿੱਤਰ\nਯਾਤਰਾ ਦੀ ਯੋਜਨਾ ਬਣਾਓ",
    bannerSub: "AC ਅਤੇ Non-AC ਬੱਸਾਂ · ਭਰੋਸੇਯੋਗ ਸੰਚਾਲਕ · ਆਸਾਨ ਸੀਟ ਬੁਕਿੰਗ",
    exploreToursBtn: "ਯਾਤਰਾਵਾਂ ਦੇਖੋ",
    bookingOpen: "ਬੁਕਿੰਗ ਖੁੱਲੀ ਹੈ",
    yatrasReady: "ਆਉਣ ਵਾਲੀ ਯਾਤਰਾ ਦਰਸ਼ਨ ਲਈ ਤਿਆਰ",
    upcomingYatras: "ਆਉਣ ਵਾਲੀਆਂ ਯਾਤਰਾਵਾਂ",
    upcomingYatrasSub: "ਅਗਲੀ ਯਾਤਰਾ ਦੀ ਯੋਜਨਾ ਬਣਾਓ",
    viewAll: "ਸਾਰੇ ਦੇਖੋ →",
    noUpcomingYatras: "ਇਸ ਸਮੇਂ ਕੋਈ ਯਾਤਰਾ ਨਹੀਂ",
    devotionalServices: "ਭਗਤੀ ਸੇਵਾਵਾਂ",
    devotionalServicesSub: "ਅਧਿਆਤਮਿਕ ਸੇਵਾਵਾਂ",
    dailyAarti: "ਰੋਜ਼ਾਨਾ ਆਰਤੀ",
    readChalisa: "ਚਾਲੀਸਾ ਪੜ੍ਹੋ",
    devotionalBhajans: "ਭਗਤੀ ਭਜਨ",
    devoteesVoice: "ਭਗਤਾਂ ਦੀ ਆਵਾਜ਼",
    devoteesVoiceSub: "ਧੰਨ ਅਨੁਭਵ",
    mantra: "ਤੁਹਾਡੀ ਯਾਤਰਾ, ਸਾਡਾ ਵਾਅਦਾ",
    mantraEn: "ਸਹਿਜ ਯਾਤਰਾਵਾਂ · ਪਵਿੱਤਰ ਮੰਜ਼ਿਲਾਂ",
    home: "ਘਰ",
    tours: "ਯਾਤਰਾਵਾਂ",
    bookings: "ਬੁਕਿੰਗਾਂ",
    profile: "ਪ੍ਰੋਫਾਈਲ",
    devotion: "ਭਗਤੀ",
    loading: "ਲੋਡ ਹੋ ਰਿਹਾ ਹੈ...",
    back: "ਵਾਪਸ",
    save: "ਸੁਰੱਖਿਅਤ ਕਰੋ",
    cancel: "ਰੱਦ ਕਰੋ",
    delete: "ਮਿਟਾਓ",
    edit: "ਬਦਲੋ",
    confirm: "ਪੁਸ਼ਟੀ ਕਰੋ",
    error: "ਗਲਤੀ",
    success: "ਸਫਲਤਾ",
    refresh: "ਰੀਫ੍ਰੈਸ਼",
    submit: "ਜਮ੍ਹਾਂ ਕਰੋ",
    close: "ਬੰਦ ਕਰੋ",
    login: "ਲੌਗਿਨ",
    logout: "ਲੌਗਆਉਟ",
    register: "ਰਜਿਸਟਰ",
    bookNow: "ਹੁਣੇ ਬੁੱਕ ਕਰੋ",
    upcoming: "ਆਉਣ ਵਾਲੀਆਂ ਯਾਤਰਾਵਾਂ",
    noTours: "ਕੋਈ ਯਾਤਰਾ ਉਪਲਬਧ ਨਹੀਂ",
    seatsLeft: "ਸੀਟਾਂ ਬਚੀਆਂ",
    perSeat: "ਪ੍ਰਤੀ ਸੀਟ",
    duration: "ਮਿਆਦ",
    aboutYatra: "ਇਸ ਯਾਤਰਾ ਬਾਰੇ",
    whatsIncluded: "ਕੀ ਸ਼ਾਮਲ ਹੈ",
    itinerary: "ਕਾਰਜਕ੍ਰਮ",
    myBookings: "ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ",
    noBookings: "ਅਜੇ ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ",
    confirmBooking: "ਬੁਕਿੰਗ ਪੁਸ਼ਟੀ ਕਰੋ",
    bookingConfirmed: "ਬੁਕਿੰਗ ਪੁਸ਼ਟ",
    editProfile: "ਪ੍ਰੋਫਾਈਲ ਸੰਪਾਦਿਤ ਕਰੋ",
    changePassword: "ਪਾਸਵਰਡ ਬਦਲੋ",
    adminPanel: "ਐਡਮਿਨ ਪੈਨਲ",
    logoutConfirm: "ਕੀ ਤੁਸੀਂ ਲੌਗਆਉਟ ਕਰਨਾ ਚਾਹੁੰਦੇ ਹੋ?",
    memberSince: "ਮੈਂਬਰ ਬਣੇ",
    personalDetails: "ਨਿੱਜੀ ਵੇਰਵੇ",
    travelDetails: "ਯਾਤਰਾ ਵੇਰਵੇ",
    reviewPay: "ਸਮੀਖਿਆ ਅਤੇ ਭੁਗਤਾਨ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    mobile: "ਮੋਬਾਈਲ ਨੰਬਰ",
    emailOpt: "ਈਮੇਲ (ਵਿਕਲਪਿਕ)",
    address: "ਪਤਾ",
    age: "ਉਮਰ",
    fatherName: "ਪਿਤਾ / ਪਤੀ ਦਾ ਨਾਮ",
    gender: "ਲਿੰਗ",
    aadhar: "ਆਧਾਰ ਨੰਬਰ",
    vrat: "ਵਰਤ ਰੱਖੋਗੇ?",
    vatHint: "ਕੀ ਤੁਸੀਂ ਯਾਤਰਾ ਦੌਰਾਨ ਵਰਤ ਰੱਖੋਗੇ?",
    noOfSeats: "ਸੀਟਾਂ ਦੀ ਗਿਣਤੀ",
    boardingPoint: "ਚੜ੍ਹਨ ਦੀ ਥਾਂ",
    totalAmount: "ਕੁੱਲ ਰਕਮ",
    continueBtn: "ਜਾਰੀ ਰੱਖੋ",
    confirmPay: "ਪੁਸ਼ਟੀ ਕਰੋ ਅਤੇ ਭੁਗਤਾਨ ਕਰੋ",
    additionalPassengers: "ਵਾਧੂ ਯਾਤਰੀ",
    passengerNum: "ਯਾਤਰੀ",
    gallery: "ਗੈਲਰੀ",
    photos: "ਫੋਟੋਆਂ",
    videos: "ਵੀਡੀਓ",
    bhajans: "ਭਜਨ",
    chalisa: "ਚਾਲੀਸਾ",
    aarti: "ਆਰਤੀ",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    users: "ਉਪਭੋਗਤਾ",
    members: "ਮੈਂਬਰ",
    enquiries: "ਪੁੱਛਗਿੱਛ",
    feedback: "ਫੀਡਬੈਕ",
    donations: "ਦਾਨ",
    settings: "ਸੈਟਿੰਗਾਂ",
    noResults: "ਕੋਈ ਨਤੀਜਾ ਨਹੀਂ",
    tryAgain: "ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ",
    contactUs: "ਸਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
    about: "ਸਾਡੇ ਬਾਰੇ",
    myBookingsSub: "ਤੁਹਾਡੀਆਂ ਯਾਤਰਾਵਾਂ",
    loginToViewBookings: "ਬੁਕਿੰਗਾਂ ਦੇਖਣ ਲਈ ਲੌਗਿਨ ਕਰੋ",
    loginRegister: "ਲੌਗਿਨ / ਰਜਿਸਟਰ",
    noBookingYet: "ਅਜੇ ਕੋਈ ਬੁਕਿੰਗ ਨਹੀਂ",
    sacredJourneyAwaits: "ਤੁਹਾਡੀ ਪਵਿੱਤਰ ਯਾਤਰਾ ਉਡੀਕ ਕਰ ਰਹੀ ਹੈ",
    exploreYatras: "ਯਾਤਰਾਵਾਂ ਦੇਖੋ",
    viewTicket: "ਟਿਕਟ ਦੇਖੋ",
    welcomeBack: "ਵਾਪਸ ਜੀ ਆਇਆਂ",
    welcomeBackSub: "ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ, ਭਗਤ",
    joinUs: "ਸਾਡੇ ਨਾਲ ਜੁੜੋ",
    joinUsSub: "ਸ਼ਿਆਮ ਪਰਿਵਾਰ ਵਿੱਚ ਤੁਹਾਡਾ ਸੁਆਗਤ ਹੈ",
    resetPwd: "ਪਾਸਵਰਡ ਰੀਸੈੱਟ",
    resetPwdSub: "ਅਸੀਂ ਤੁਹਾਡੇ ਈਮੇਲ 'ਤੇ ਰੀਸੈੱਟ ਲਿੰਕ ਭੇਜਾਂਗੇ",
    marriageAidSub: "ਵਿਆਹ ਸਹਾਇਤਾ",
    aartiSub: "ਰੋਜ਼ਾਨਾ ਆਰਤੀ",
    chalisaSub: "ਖਾਟੂ ਸ਼ਿਆਮ ਚਾਲੀਸਾ",
    donationSuccessTitle: "ਦਾਨ ਸਫਲ",
    donationSuccessMsg: "ਜੈ ਸ਼੍ਰੀ ਸ਼ਿਆਮ! ਤੁਹਾਡਾ ਦਾਨ ਪ੍ਰਾਪਤ ਹੋ ਗਿਆ।",
    donateHeroSub: "ਹਰ ਸੇਵਾ, ਸ਼ਿਆਮ ਜੀ ਦੀ ਕਿਰਪਾ।",
    anonymousDonate: "ਗੁਪਤ ਦਾਨ ਕਰੋ",
    gallerySub: "ਦਰਸ਼ਨ ਅਤੇ ਯਾਦਾਂ",
    aboutHeroSub: "ਟ੍ਰਿਪਕਾਰਟ ਪਰਿਵਾਰ",
    aboutMissionDesc:
      "ਟ੍ਰਿਪਕਾਰਟ ਪਰਿਵਾਰ ਇੱਕ ਅਧਿਆਤਮਿਕ ਪਰਿਵਾਰ ਹੈ ਜੋ ਖਾਟੂ ਸ਼ਿਆਮ ਜੀ ਅਤੇ ਸਮਾਜ ਦੀ ਸੇਵਾ ਲਈ ਸਮਰਪਿਤ ਹੈ। ਅਸੀਂ ਮਾਸਿਕ ਯਾਤਰਾਵਾਂ, ਭਗਤੀ ਸਮਾਗਮਾਂ ਅਤੇ ਸਮਾਜਿਕ ਸੇਵਾਵਾਂ ਆਯੋਜਿਤ ਕਰਦੇ ਹਾਂ।",
    membershipHeroSub: "ਪਰਿਵਾਰ ਦਾ ਹਿੱਸਾ ਬਣੋ",
    membershipSuccessSub:
      "ਤੁਹਾਡੀ ਅਰਜ਼ੀ ਸਫਲਤਾਪੂਰਵਕ ਜਮ੍ਹਾਂ ਕਰ ਦਿੱਤੀ ਗਈ।\nਅਸੀਂ ਜਲਦੀ ਤੁਹਾਡੇ ਨਾਲ ਸੰਪਰਕ ਕਰਾਂਗੇ।",
    devotionHeaderSub: "ਭਗਤੀ · ਸੰਗੀਤ · ਆਰਤੀ",
    bhajanChipSub: "ਭਜਨ",
    aartiChipSub: "ਆਰਤੀ",
    chalisaChipSub: "ਚਾਲੀਸਾ",
    kirtanChipSub: "ਕੀਰਤਨ",
    feedbackNote: "ਜੈ ਸ਼੍ਰੀ ਸ਼ਿਆਮ · ਤੁਹਾਡੀ ਫੀਡਬੈਕ ਸਾਡੀ ਸੇਵਾ ਬਿਹਤਰ ਬਣਾਉਂਦੀ ਹੈ",
  },

  GU: {
    jai: "જય શ્રી શ્યામ",
    appName: "માસિક યાત્રા પરિવાર",
    quickAccess: "ઝડપી પ્રવેશ",
    bookBus: "બસ બુક કરો",
    bookBusSub: "સીટ બુક કરો",
    membership: "સભ્યપદ",
    membershipSub: "પરિવારમાં જોડાઓ",
    donate: "દાન કરો",
    donateSub: "સેવામાં દાન",
    contact: "સંપર્ક",
    contactSub: "સંપર્ક કરો",
    monthlyYatra: "· ટ્રિપકાર્ટ ·",
    bannerTitle: "તમારી પવિત્ર\nયાત્રાની યોજના બનાવો",
    bannerSub: "AC અને Non-AC બસો · વિશ્વસનીય ઓપરેટર · સહેલી સીટ બુકિંગ",
    exploreToursBtn: "યાત્રાઓ જુઓ",
    bookingOpen: "બુકિંગ ખુલ્લી છે",
    yatrasReady: "આગામી યાત્રા દર્શન માટે તૈયાર",
    upcomingYatras: "આગામી યાત્રાઓ",
    upcomingYatrasSub: "આગળની યાત્રાની યોજના બનાવો",
    viewAll: "બધા જુઓ →",
    noUpcomingYatras: "હાલ કોઈ આગામી યાત્રા નથી",
    devotionalServices: "ભક્તિ સેવાઓ",
    devotionalServicesSub: "આધ્યાત્મિક સેવાઓ",
    dailyAarti: "દૈનિક આરતી",
    readChalisa: "ચાલીસા વાંચો",
    devotionalBhajans: "ભક્તિ ભજન",
    devoteesVoice: "ભક્તોનો અવાજ",
    devoteesVoiceSub: "ધન્ય અનુભવો",
    mantra: "તમારી યાત્રા, અમારું વચન",
    mantraEn: "સરળ યાત્રાઓ · પવિત્ર મંઝિલો",
    home: "ઘર",
    tours: "યાત્રાઓ",
    bookings: "બુકિંગ",
    profile: "પ્રોફાઇલ",
    devotion: "ભક્તિ",
    loading: "લોડ થઈ રહ્યું છે...",
    back: "પાછળ",
    save: "સાચવો",
    cancel: "રદ કરો",
    delete: "કાઢો",
    edit: "ફેરફાર",
    confirm: "પુષ્ટિ કરો",
    error: "ભૂલ",
    success: "સફળતા",
    refresh: "રિફ્રેશ",
    submit: "સબમિટ",
    close: "બંધ",
    login: "લૉગ ઇન",
    logout: "લૉગ આઉટ",
    register: "નોંધણી",
    bookNow: "હવે બુક કરો",
    upcoming: "આગામી યાત્રાઓ",
    noTours: "કોઈ યાત્રા ઉપલબ્ધ નથી",
    seatsLeft: "સીટો બાકી",
    perSeat: "પ્રતિ સીટ",
    duration: "અવધિ",
    aboutYatra: "આ યાત્રા વિશે",
    whatsIncluded: "શું સામેલ છે",
    itinerary: "કાર્યક્રમ",
    myBookings: "મારી બુકિંગ",
    noBookings: "હજુ સુધી કોઈ બુકિંગ નથી",
    confirmBooking: "બુકિંગ પુષ્ટિ કરો",
    bookingConfirmed: "બુકિંગ પુષ્ટ",
    editProfile: "પ્રોફાઇલ સંપાદિત કરો",
    changePassword: "પાસવર્ડ બદલો",
    adminPanel: "એડમિન પેનલ",
    logoutConfirm: "શું તમે લૉગ આઉટ કરવા માગો છો?",
    memberSince: "સભ્ય બન્યા",
    personalDetails: "વ્યક્તિગત વિગતો",
    travelDetails: "યાત્રા વિગતો",
    reviewPay: "સમીક્ષા અને ચૂકવણી",
    fullName: "પૂરું નામ",
    mobile: "મોબાઇલ નંબર",
    emailOpt: "ઇ-મેઇલ (વૈકલ્પિક)",
    address: "સરનામું",
    age: "ઉંમર",
    fatherName: "પિતા / પતિનું નામ",
    gender: "લિંગ",
    aadhar: "આધાર નંબર",
    vrat: "વ્રત રાખશો?",
    vatHint: "શું તમે યાત્રા દરમિયાન ઉપવાસ કરશો?",
    noOfSeats: "સીટોની સંખ્યા",
    boardingPoint: "ચઢવાની જગ્યા",
    totalAmount: "કુલ રકમ",
    continueBtn: "ચાલુ રાખો",
    confirmPay: "પુષ્ટિ કરો અને ચૂકવો",
    additionalPassengers: "વધારાના પ્રવાસીઓ",
    passengerNum: "પ્રવાસી",
    gallery: "ગૅલરી",
    photos: "ફોટો",
    videos: "વીડિઓ",
    bhajans: "ભજન",
    chalisa: "ચાલીસા",
    aarti: "આરતી",
    dashboard: "ડૅશબોર્ડ",
    users: "વપરાશકારો",
    members: "સભ્યો",
    enquiries: "પૂછપરછ",
    feedback: "પ્રતિક્રિયા",
    donations: "દાન",
    settings: "સેટિંગ્સ",
    noResults: "કોઈ પરિણામ નહીં",
    tryAgain: "ફરી પ્રયાસ કરો",
    contactUs: "અમારો સંપર્ક",
    about: "અમારા વિશે",
    myBookingsSub: "તમારી યાત્રાઓ",
    loginToViewBookings: "બુકિંગ જોવા માટે લૉગ ઇન કરો",
    loginRegister: "લૉગ ઇન / નોંધણી",
    noBookingYet: "હજુ સુધી કોઈ બુકિંગ નથી",
    sacredJourneyAwaits: "તમારી પવિત્ર યાત્રા રાહ જોઈ રહી છે",
    exploreYatras: "યાત્રાઓ જુઓ",
    viewTicket: "ટિકિટ જુઓ",
    welcomeBack: "પુનઃ સ્વાગત",
    welcomeBackSub: "પુનઃ સ્વાગત, ભક્ત",
    joinUs: "જોડાઓ",
    joinUsSub: "શ્યામ પરિવારમાં સ્વાગત",
    resetPwd: "પાસવર્ડ રીસેટ",
    resetPwdSub: "અમે તમારા ઇ-મેઇલ પર રીસેટ લિંક મોકલીશું",
    marriageAidSub: "લગ્ન સહાય",
    aartiSub: "દૈનિક આરતી",
    chalisaSub: "ખાટૂ શ્યામ ચાલીસા",
    donationSuccessTitle: "દાન સફળ",
    donationSuccessMsg: "જય શ્રી શ્યામ! તમારું દાન પ્રાપ્ત થઈ ગયું.",
    donateHeroSub: "દરેક સેવા, શ્યામ જીની કૃપા.",
    anonymousDonate: "ગુપ્ત દાન કરો",
    gallerySub: "દર્શન અને સ્મૃતિઓ",
    aboutHeroSub: "ટ્રિપકાર્ટ પરિવાર",
    aboutMissionDesc:
      "ટ્રિપકાર્ટ પરિવાર એ એક આધ્યાત્મિક પરિવાર છે જે ખાટૂ શ્યામ જી અને સમાજની સેવા માટે સમર્પિત છે. અમે માસિક યાત્રાઓ, ભક્તિ કાર્યક્રમો અને સામાજિક સેવાઓ આયોજિત કરીએ છીએ.",
    membershipHeroSub: "પરિવારનો ભાગ બનો",
    membershipSuccessSub:
      "તમારી અરજી સફળતાપૂર્વક સબમિટ કરવામાં આવી.\nઅમે ટૂંક સમયમાં સંપર્ક કરીશું.",
    devotionHeaderSub: "ભક્તિ · સંગીત · આરતી",
    bhajanChipSub: "ભજન",
    aartiChipSub: "આરતી",
    chalisaChipSub: "ચાલીસા",
    kirtanChipSub: "કીર્તન",
    feedbackNote: "જય શ્રી શ્યામ · તમારી પ્રતિક્રિયા અમારી સેવા સુધારે છે",
  },

  MR: {
    jai: "जय श्री श्याम",
    appName: "मासिक यात्रा परिवार",
    quickAccess: "जलद प्रवेश",
    bookBus: "बस बुक करा",
    bookBusSub: "सीट बुक करा",
    membership: "सदस्यत्व",
    membershipSub: "परिवारात सामील व्हा",
    donate: "दान करा",
    donateSub: "सेवेत दान",
    contact: "संपर्क",
    contactSub: "संपर्क करा",
    monthlyYatra: "· ट्रिपकार्ट ·",
    bannerTitle: "तुमच्या पवित्र\nयात्रेची योजना करा",
    bannerSub: "AC व Non-AC बस · विश्वसनीय ऑपरेटर · सोपी सीट बुकिंग",
    exploreToursBtn: "यात्रा पाहा",
    bookingOpen: "बुकिंग उघडी आहे",
    yatrasReady: "येणारी यात्रा दर्शनासाठी तयार",
    upcomingYatras: "येणाऱ्या यात्रा",
    upcomingYatrasSub: "पुढील यात्रेची योजना करा",
    viewAll: "सर्व पाहा →",
    noUpcomingYatras: "सध्या कोणतीही येणारी यात्रा नाही",
    devotionalServices: "भक्ती सेवा",
    devotionalServicesSub: "आध्यात्मिक सेवा",
    dailyAarti: "दैनंदिन आरती",
    readChalisa: "चाळीसा वाचा",
    devotionalBhajans: "भक्ती भजन",
    devoteesVoice: "भक्तांचा आवाज",
    devoteesVoiceSub: "धन्य अनुभव",
    mantra: "तुमचा प्रवास, आमचे वचन",
    mantraEn: "सुलभ यात्रा · पवित्र गंतव्ये",
    home: "मुख्यपृष्ठ",
    tours: "यात्रा",
    bookings: "बुकिंग",
    profile: "प्रोफाइल",
    devotion: "भक्ती",
    loading: "लोड होत आहे...",
    back: "मागे",
    save: "जतन करा",
    cancel: "रद्द करा",
    delete: "काढा",
    edit: "बदला",
    confirm: "पुष्टी करा",
    error: "चूक",
    success: "यश",
    refresh: "रीफ्रेश",
    submit: "सादर करा",
    close: "बंद करा",
    login: "लॉगिन",
    logout: "लॉगआउट",
    register: "नोंदणी",
    bookNow: "आता बुक करा",
    upcoming: "येणाऱ्या यात्रा",
    noTours: "कोणतीही यात्रा उपलब्ध नाही",
    seatsLeft: "जागा शिल्लक",
    perSeat: "प्रति जागा",
    duration: "कालावधी",
    aboutYatra: "या यात्रेबद्दल",
    whatsIncluded: "काय समाविष्ट आहे",
    itinerary: "कार्यक्रम",
    myBookings: "माझ्या बुकिंग",
    noBookings: "अद्याप कोणतीही बुकिंग नाही",
    confirmBooking: "बुकिंग पुष्टी करा",
    bookingConfirmed: "बुकिंग पुष्ट",
    editProfile: "प्रोफाइल संपादित करा",
    changePassword: "पासवर्ड बदला",
    adminPanel: "अॅडमिन पॅनेल",
    logoutConfirm: "तुम्हाला लॉगआउट करायचे आहे का?",
    memberSince: "सदस्य झाले",
    personalDetails: "वैयक्तिक तपशील",
    travelDetails: "प्रवास तपशील",
    reviewPay: "पुनरावलोकन आणि पेमेंट",
    fullName: "पूर्ण नाव",
    mobile: "मोबाईल नंबर",
    emailOpt: "ईमेल (पर्यायी)",
    address: "पत्ता",
    age: "वय",
    fatherName: "वडील / पतीचे नाव",
    gender: "लिंग",
    aadhar: "आधार नंबर",
    vrat: "व्रत ठेवाल?",
    vatHint: "तुम्ही यात्रेदरम्यान उपवास कराल का?",
    noOfSeats: "जागांची संख्या",
    boardingPoint: "बोर्डिंग पॉइंट",
    totalAmount: "एकूण रक्कम",
    continueBtn: "पुढे जा",
    confirmPay: "पुष्टी करा आणि पैसे भरा",
    additionalPassengers: "अतिरिक्त प्रवासी",
    passengerNum: "प्रवासी",
    gallery: "गॅलरी",
    photos: "फोटो",
    videos: "व्हिडिओ",
    bhajans: "भजन",
    chalisa: "चाळीसा",
    aarti: "आरती",
    dashboard: "डॅशबोर्ड",
    users: "वापरकर्ते",
    members: "सदस्य",
    enquiries: "चौकशी",
    feedback: "अभिप्राय",
    donations: "दान",
    settings: "सेटिंग्ज",
    noResults: "कोणताही निकाल नाही",
    tryAgain: "पुन्हा प्रयत्न करा",
    contactUs: "आमच्याशी संपर्क करा",
    about: "आमच्याबद्दल",
    myBookingsSub: "तुमच्या यात्रा",
    loginToViewBookings: "बुकिंग पाहण्यासाठी लॉगिन करा",
    loginRegister: "लॉगिन / नोंदणी",
    noBookingYet: "अद्याप कोणतीही बुकिंग नाही",
    sacredJourneyAwaits: "तुमचा पवित्र प्रवास वाट पाहत आहे",
    exploreYatras: "यात्रा पाहा",
    viewTicket: "तिकीट पाहा",
    welcomeBack: "पुन्हा स्वागत",
    welcomeBackSub: "पुन्हा स्वागत, भक्त",
    joinUs: "सामील व्हा",
    joinUsSub: "श्याम परिवारात स्वागत",
    resetPwd: "पासवर्ड रीसेट",
    resetPwdSub: "आम्ही तुमच्या ईमेलवर रीसेट लिंक पाठवू",
    marriageAidSub: "विवाह सहाय्य",
    aartiSub: "दैनंदिन आरती",
    chalisaSub: "खाटू श्याम चाळीसा",
    donationSuccessTitle: "दान यशस्वी",
    donationSuccessMsg: "जय श्री श्याम! तुमचे दान मिळाले.",
    donateHeroSub: "प्रत्येक सेवा, श्याम जींची कृपा.",
    anonymousDonate: "गुप्त दान करा",
    gallerySub: "दर्शन आणि आठवणी",
    aboutHeroSub: "ट्रिपकार्ट परिवार",
    aboutMissionDesc:
      "ट्रिपकार्ट परिवार ही एक आध्यात्मिक कुटुंब आहे जी खाटू श्याम जी आणि समाजाच्या सेवेसाठी समर्पित आहे. आम्ही मासिक यात्रा, भक्ती कार्यक्रम आणि सामाजिक सेवा आयोजित करतो.",
    membershipHeroSub: "परिवाराचा भाग व्हा",
    membershipSuccessSub:
      "तुमचा अर्ज यशस्वीरीत्या सादर केला.\nआम्ही लवकरच संपर्क साधू.",
    devotionHeaderSub: "भक्ती · संगीत · आरती",
    bhajanChipSub: "भजन",
    aartiChipSub: "आरती",
    chalisaChipSub: "चाळीसा",
    kirtanChipSub: "कीर्तन",
    feedbackNote: "जय श्री श्याम · तुमचा अभिप्राय आमची सेवा सुधारतो",
  },

  BN: {
    jai: "জয় শ্রী শ্যাম",
    appName: "মাসিক যাত্রা পরিবার",
    quickAccess: "দ্রুত প্রবেশ",
    bookBus: "বাস বুক করুন",
    bookBusSub: "সিট বুক করুন",
    membership: "সদস্যপদ",
    membershipSub: "পরিবারে যোগ দিন",
    donate: "দান করুন",
    donateSub: "সেবায় দান",
    contact: "যোগাযোগ",
    contactSub: "যোগাযোগ করুন",
    monthlyYatra: "· ট্রিপকার্ট ·",
    bannerTitle: "আপনার পবিত্র\nযাত্রার পরিকল্পনা করুন",
    bannerSub: "AC ও Non-AC বাস · বিশ্বস্ত অপারেটর · সহজ সিট বুকিং",
    exploreToursBtn: "যাত্রা দেখুন",
    bookingOpen: "বুকিং খোলা আছে",
    yatrasReady: "আসন্ন যাত্রা দর্শনের জন্য প্রস্তুত",
    upcomingYatras: "আসন্ন যাত্রা",
    upcomingYatrasSub: "পরবর্তী যাত্রার পরিকল্পনা করুন",
    viewAll: "সব দেখুন →",
    noUpcomingYatras: "এই মুহূর্তে কোনো আসন্ন যাত্রা নেই",
    devotionalServices: "ভক্তি সেবা",
    devotionalServicesSub: "আধ্যাত্মিক সেবা",
    dailyAarti: "দৈনিক আরতি",
    readChalisa: "চালিশা পড়ুন",
    devotionalBhajans: "ভক্তি ভজন",
    devoteesVoice: "ভক্তদের কণ্ঠস্বর",
    devoteesVoiceSub: "আশীর্বাদপূর্ণ অভিজ্ঞতা",
    mantra: "আপনার যাত্রা, আমাদের প্রতিশ্রুতি",
    mantraEn: "নিরবচ্ছিন্ন যাত্রা · পবিত্র গন্তব্য",
    home: "হোম",
    tours: "যাত্রা",
    bookings: "বুকিং",
    profile: "প্রোফাইল",
    devotion: "ভক্তি",
    loading: "লোড হচ্ছে...",
    back: "পিছনে",
    save: "সংরক্ষণ",
    cancel: "বাতিল",
    delete: "মুছুন",
    edit: "সম্পাদনা",
    confirm: "নিশ্চিত করুন",
    error: "ত্রুটি",
    success: "সাফল্য",
    refresh: "রিফ্রেশ",
    submit: "জমা দিন",
    close: "বন্ধ",
    login: "লগইন",
    logout: "লগআউট",
    register: "নিবন্ধন",
    bookNow: "এখনই বুক করুন",
    upcoming: "আসন্ন যাত্রা",
    noTours: "কোনো যাত্রা উপলব্ধ নেই",
    seatsLeft: "আসন বাকি",
    perSeat: "প্রতি আসন",
    duration: "সময়কাল",
    aboutYatra: "এই যাত্রা সম্পর্কে",
    whatsIncluded: "কী অন্তর্ভুক্ত",
    itinerary: "কর্মসূচি",
    myBookings: "আমার বুকিং",
    noBookings: "এখনো কোনো বুকিং নেই",
    confirmBooking: "বুকিং নিশ্চিত করুন",
    bookingConfirmed: "বুকিং নিশ্চিত",
    editProfile: "প্রোফাইল সম্পাদনা",
    changePassword: "পাসওয়ার্ড পরিবর্তন",
    adminPanel: "অ্যাডমিন প্যানেল",
    logoutConfirm: "আপনি কি লগআউট করতে চান?",
    memberSince: "সদস্য হয়েছেন",
    personalDetails: "ব্যক্তিগত বিবরণ",
    travelDetails: "যাত্রার বিবরণ",
    reviewPay: "পর্যালোচনা এবং পেমেন্ট",
    fullName: "পূর্ণ নাম",
    mobile: "মোবাইল নম্বর",
    emailOpt: "ইমেইল (ঐচ্ছিক)",
    address: "ঠিকানা",
    age: "বয়স",
    fatherName: "পিতা / স্বামীর নাম",
    gender: "লিঙ্গ",
    aadhar: "আধার নম্বর",
    vrat: "ব্রত রাখবেন?",
    vatHint: "আপনি কি যাত্রার সময় উপবাস করবেন?",
    noOfSeats: "আসন সংখ্যা",
    boardingPoint: "বোর্ডিং পয়েন্ট",
    totalAmount: "মোট পরিমাণ",
    continueBtn: "চালিয়ে যান",
    confirmPay: "নিশ্চিত করুন এবং পেমেন্ট করুন",
    additionalPassengers: "অতিরিক্ত যাত্রী",
    passengerNum: "যাত্রী",
    gallery: "গ্যালারি",
    photos: "ফটো",
    videos: "ভিডিও",
    bhajans: "ভজন",
    chalisa: "চালিশা",
    aarti: "আরতি",
    dashboard: "ড্যাশবোর্ড",
    users: "ব্যবহারকারী",
    members: "সদস্য",
    enquiries: "অনুসন্ধান",
    feedback: "প্রতিক্রিয়া",
    donations: "দান",
    settings: "সেটিংস",
    noResults: "কোনো ফলাফল নেই",
    tryAgain: "আবার চেষ্টা করুন",
    contactUs: "আমাদের সাথে যোগাযোগ",
    about: "আমাদের সম্পর্কে",
    myBookingsSub: "আপনার যাত্রাগুলি",
    loginToViewBookings: "বুকিং দেখতে লগইন করুন",
    loginRegister: "লগইন / নিবন্ধন",
    noBookingYet: "এখনো কোনো বুকিং নেই",
    sacredJourneyAwaits: "আপনার পবিত্র যাত্রা অপেক্ষা করছে",
    exploreYatras: "যাত্রা দেখুন",
    viewTicket: "টিকিট দেখুন",
    welcomeBack: "পুনরায় স্বাগতম",
    welcomeBackSub: "স্বাগতম, ভক্ত",
    joinUs: "যোগ দিন",
    joinUsSub: "শ্যাম পরিবারে স্বাগতম",
    resetPwd: "পাসওয়ার্ড রিসেট",
    resetPwdSub: "আমরা আপনার ইমেইলে রিসেট লিংক পাঠাব",
    marriageAidSub: "বিবাহ সহায়তা",
    aartiSub: "দৈনিক আরতি",
    chalisaSub: "খাটু শ্যাম চালিশা",
    donationSuccessTitle: "দান সফল",
    donationSuccessMsg: "জয় শ্রী শ্যাম! আপনার দান প্রাপ্ত হয়েছে।",
    donateHeroSub: "প্রতিটি সেবা, শ্যাম জীর অনুগ্রহে।",
    anonymousDonate: "গোপনীয় দান করুন",
    gallerySub: "দর্শন এবং স্মৃতি",
    aboutHeroSub: "ট্রিপকার্ট পরিবার",
    aboutMissionDesc:
      "ট্রিপকার্ট পরিবার একটি আধ্যাত্মিক পরিবার যা খাটু শ্যাম জী এবং সমাজের সেবায় নিবেদিত। আমরা মাসিক যাত্রা, ভক্তি অনুষ্ঠান এবং সামাজিক সেবা পরিচালনা করি।",
    membershipHeroSub: "পরিবারের অংশ হন",
    membershipSuccessSub:
      "আপনার আবেদন সফলভাবে জমা হয়েছে।\nআমরা শীঘ্রই যোগাযোগ করব।",
    devotionHeaderSub: "ভক্তি · সংগীত · আরতি",
    bhajanChipSub: "ভজন",
    aartiChipSub: "আরতি",
    chalisaChipSub: "চালিশা",
    kirtanChipSub: "কীর্তন",
    feedbackNote: "জয় শ্রী শ্যাম · আপনার প্রতিক্রিয়া আমাদের সেবা উন্নত করে",
  },

  TA: {
    jai: "ஜெய் ஸ்ரீ ஷ்யாம்",
    appName: "மாதாந்திர யாத்திரை பரிவார்",
    quickAccess: "விரைவு அணுகல்",
    bookBus: "பஸ் முன்பதிவு",
    bookBusSub: "இருக்கை முன்பதிவு",
    membership: "உறுப்பினர்",
    membershipSub: "குடும்பத்தில் சேரு",
    donate: "தானம் செய்",
    donateSub: "சேவையில் தானம்",
    contact: "தொடர்பு",
    contactSub: "தொடர்பு கொள்",
    monthlyYatra: "· ட்ரிப்கார்ட் ·",
    bannerTitle: "உங்கள் புனித\nயாத்திரையை திட்டமிடுங்கள்",
    bannerSub:
      "AC & Non-AC பஸ்கள் · நம்பகமான நடத்துனர்கள் · எளிய இருக்கை முன்பதிவு",
    exploreToursBtn: "யாத்திரைகளை காண்க",
    bookingOpen: "முன்பதிவு திறந்துள்ளது",
    yatrasReady: "வரும் யாத்திரை தரிசனத்திற்கு தயார்",
    upcomingYatras: "வரும் யாத்திரைகள்",
    upcomingYatrasSub: "அடுத்த யாத்திரையை திட்டமிடுங்கள்",
    viewAll: "அனைத்தும் காண்க →",
    noUpcomingYatras: "இப்போது வரும் யாத்திரைகள் இல்லை",
    devotionalServices: "பக்தி சேவைகள்",
    devotionalServicesSub: "ஆன்மீக சேவைகள்",
    dailyAarti: "தினசரி ஆரத்தி",
    readChalisa: "சாலீசா படிக்க",
    devotionalBhajans: "பக்தி பஜன்கள்",
    devoteesVoice: "பக்தர்களின் குரல்",
    devoteesVoiceSub: "ஆசீர்வதிக்கப்பட்ட அனுபவங்கள்",
    mantra: "உங்கள் பயணம், எங்கள் வாக்குறுதி",
    mantraEn: "தடையற்ற யாத்திரைகள் · புனித இடங்கள்",
    home: "முகப்பு",
    tours: "யாத்திரைகள்",
    bookings: "முன்பதிவுகள்",
    profile: "சுயவிவரம்",
    devotion: "பக்தி",
    loading: "ஏற்றுகிறது...",
    back: "பின்செல்",
    save: "சேமி",
    cancel: "ரத்து செய்",
    delete: "நீக்கு",
    edit: "திருத்து",
    confirm: "உறுதிப்படுத்து",
    error: "பிழை",
    success: "வெற்றி",
    refresh: "புதுப்பி",
    submit: "சமர்ப்பி",
    close: "மூடு",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    register: "பதிவு செய்",
    bookNow: "இப்போது முன்பதிவு செய்",
    upcoming: "வரும் யாத்திரைகள்",
    noTours: "யாத்திரைகள் எதுவும் இல்லை",
    seatsLeft: "இருக்கைகள் உள்ளன",
    perSeat: "ஒரு இருக்கைக்கு",
    duration: "கால அளவு",
    aboutYatra: "இந்த யாத்திரையைப் பற்றி",
    whatsIncluded: "என்ன சேர்க்கப்பட்டுள்ளது",
    itinerary: "பயண அட்டவணை",
    myBookings: "என் முன்பதிவுகள்",
    noBookings: "இன்னும் முன்பதிவு இல்லை",
    confirmBooking: "முன்பதிவை உறுதிப்படுத்து",
    bookingConfirmed: "முன்பதிவு உறுதி",
    editProfile: "சுயவிவரம் திருத்து",
    changePassword: "கடவுச்சொல் மாற்று",
    adminPanel: "நிர்வாக பலகை",
    logoutConfirm: "வெளியேற விரும்புகிறீர்களா?",
    memberSince: "உறுப்பினரான தேதி",
    personalDetails: "தனிப்பட்ட விவரங்கள்",
    travelDetails: "பயண விவரங்கள்",
    reviewPay: "மதிப்பாய்வு மற்றும் கட்டணம்",
    fullName: "முழு பெயர்",
    mobile: "கைபேசி எண்",
    emailOpt: "மின்னஞ்சல் (விருப்பமான)",
    address: "முகவரி",
    age: "வயது",
    fatherName: "தந்தை / கணவர் பெயர்",
    gender: "பாலினம்",
    aadhar: "ஆதார் எண்",
    vrat: "விரதம் இருப்பீர்களா?",
    vatHint: "யாத்திரையின் போது விரதம் இருப்பீர்களா?",
    noOfSeats: "இருக்கைகள் எண்ணிக்கை",
    boardingPoint: "ஏறும் இடம்",
    totalAmount: "மொத்த தொகை",
    continueBtn: "தொடர்",
    confirmPay: "உறுதிப்படுத்தி பணம் செலுத்து",
    additionalPassengers: "கூடுதல் பயணிகள்",
    passengerNum: "பயணி",
    gallery: "தொகுப்பு",
    photos: "புகைப்படங்கள்",
    videos: "வீடியோக்கள்",
    bhajans: "பஜன்கள்",
    chalisa: "சாலீசா",
    aarti: "ஆரத்தி",
    dashboard: "டாஷ்போர்டு",
    users: "பயனர்கள்",
    members: "உறுப்பினர்கள்",
    enquiries: "விசாரணைகள்",
    feedback: "கருத்து",
    donations: "தானங்கள்",
    settings: "அமைப்புகள்",
    noResults: "முடிவுகள் இல்லை",
    tryAgain: "மீண்டும் முயற்சி செய்",
    contactUs: "எங்களை தொடர்பு கொள்ளவும்",
    about: "எங்களைப் பற்றி",
    myBookingsSub: "உங்கள் பயணங்கள்",
    loginToViewBookings: "முன்பதிவுகள் காண உள்நுழைக",
    loginRegister: "உள்நுழைவு / பதிவு",
    noBookingYet: "இன்னும் முன்பதிவு இல்லை",
    sacredJourneyAwaits: "உங்கள் புனித பயணம் காத்திருக்கிறது",
    exploreYatras: "யாத்திரைகளை காண்க",
    viewTicket: "டிக்கெட் காண்க",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    welcomeBackSub: "வரவேற்கிறோம், பக்தர்",
    joinUs: "இணைக",
    joinUsSub: "ஷ்யாம் பரிவாரில் வரவேற்கிறோம்",
    resetPwd: "கடவுச்சொல் மீட்டமை",
    resetPwdSub: "உங்கள் மின்னஞ்சலுக்கு மீட்டமை இணைப்பு அனுப்புவோம்",
    marriageAidSub: "திருமண உதவி",
    aartiSub: "தினசரி ஆரத்தி",
    chalisaSub: "காட்டு ஷ்யாம் சாலீசா",
    donationSuccessTitle: "தானம் வெற்றி",
    donationSuccessMsg: "ஜெய் ஸ்ரீ ஷ்யாம்! உங்கள் தானம் பெறப்பட்டது.",
    donateHeroSub: "ஒவ்வொரு சேவையும் ஷ்யாம் ஜீயின் அருளால்.",
    anonymousDonate: "அடையாளம் தெரியாத தானம்",
    gallerySub: "தரிசனம் மற்றும் நினைவுகள்",
    aboutHeroSub: "ட்ரிப்கார்ட் பரிவார்",
    aboutMissionDesc:
      "ட்ரிப்கார்ட் பரிவார் காட்டு ஷ்யாம் ஜீ மற்றும் சமுதாயத்தின் சேவைக்கு அர்ப்பணிக்கப்பட்ட ஆன்மீக குடும்பம். நாங்கள் மாதாந்திர யாத்திரைகள், பக்தி நிகழ்வுகள் மற்றும் சமூக சேவைகளை ஏற்பாடு செய்கிறோம்.",
    membershipHeroSub: "குடும்பத்தின் ஒரு பகுதியாகு",
    membershipSuccessSub:
      "உங்கள் விண்ணப்பம் வெற்றிகரமாக சமர்ப்பிக்கப்பட்டது.\nநாங்கள் விரைவில் தொடர்பு கொள்வோம்.",
    devotionHeaderSub: "பக்தி · இசை · ஆரத்தி",
    bhajanChipSub: "பஜன்",
    aartiChipSub: "ஆரத்தி",
    chalisaChipSub: "சாலீசா",
    kirtanChipSub: "கீர்த்தனை",
    feedbackNote:
      "ஜெய் ஸ்ரீ ஷ்யாம் · உங்கள் கருத்து எங்கள் சேவையை மேம்படுத்துகிறது",
  },

  TE: {
    jai: "జయ శ్రీ శ్యామ్",
    appName: "మాసిక యాత్ర పరివార్",
    quickAccess: "త్వరిత యాక్సెస్",
    bookBus: "బస్ బుక్ చేయి",
    bookBusSub: "సీటు బుక్ చేయి",
    membership: "సభ్యత్వం",
    membershipSub: "కుటుంబంలో చేరు",
    donate: "దానం ఇవ్వు",
    donateSub: "సేవలో దానం",
    contact: "సంప్రదించు",
    contactSub: "సంప్రదించు",
    monthlyYatra: "· ట్రిప్‌కార్ట్ ·",
    bannerTitle: "మీ పవిత్ర\nయాత్రను ప్లాన్ చేయండి",
    bannerSub: "AC & Non-AC బస్సులు · నమ్మకమైన ఆపరేటర్లు · సులభ సీటు బుకింగ్",
    exploreToursBtn: "యాత్రలు చూడు",
    bookingOpen: "బుకింగ్ తెరుచుకుంది",
    yatrasReady: "రాబోయే యాత్ర దర్శనానికి సిద్ధం",
    upcomingYatras: "రాబోయే యాత్రలు",
    upcomingYatrasSub: "తదుపరి యాత్రను ప్లాన్ చేయండి",
    viewAll: "అన్నీ చూడు →",
    noUpcomingYatras: "ప్రస్తుతం రాబోయే యాత్రలు లేవు",
    devotionalServices: "భక్తి సేవలు",
    devotionalServicesSub: "ఆధ్యాత్మిక సేవలు",
    dailyAarti: "రోజువారీ ఆరతి",
    readChalisa: "చాలీసా చదవు",
    devotionalBhajans: "భక్తి భజనలు",
    devoteesVoice: "భక్తుల స్వరం",
    devoteesVoiceSub: "ధన్యమైన అనుభవాలు",
    mantra: "మీ యాత్ర, మా వాగ్దానం",
    mantraEn: "నిరాటంక యాత్రలు · పవిత్ర గమ్యస్థానాలు",
    home: "హోమ్",
    tours: "యాత్రలు",
    bookings: "బుకింగులు",
    profile: "ప్రొఫైల్",
    devotion: "భక్తి",
    loading: "లోడ్ అవుతోంది...",
    back: "వెనక్కి",
    save: "సేవ్ చేయి",
    cancel: "రద్దు చేయి",
    delete: "తొలగించు",
    edit: "మార్చు",
    confirm: "నిర్ధారించు",
    error: "లోపం",
    success: "విజయం",
    refresh: "రిఫ్రెష్",
    submit: "సమర్పించు",
    close: "మూసు",
    login: "లాగిన్",
    logout: "లాగ్ అవుట్",
    register: "నమోదు",
    bookNow: "ఇప్పుడే బుక్ చేయి",
    upcoming: "రాబోయే యాత్రలు",
    noTours: "యాత్రలు అందుబాటులో లేవు",
    seatsLeft: "సీట్లు మిగిలాయి",
    perSeat: "సీటుకు",
    duration: "వ్యవధి",
    aboutYatra: "ఈ యాత్ర గురించి",
    whatsIncluded: "ఏమి చేర్చబడింది",
    itinerary: "కార్యక్రమం",
    myBookings: "నా బుకింగులు",
    noBookings: "ఇంకా బుకింగులు లేవు",
    confirmBooking: "బుకింగ్ నిర్ధారించు",
    bookingConfirmed: "బుకింగ్ నిర్ధారించబడింది",
    editProfile: "ప్రొఫైల్ సవరించు",
    changePassword: "పాస్‌వర్డ్ మార్చు",
    adminPanel: "అడ్మిన్ పానెల్",
    logoutConfirm: "మీరు లాగ్ అవుట్ చేయాలనుకుంటున్నారా?",
    memberSince: "సభ్యుడు అయినారు",
    personalDetails: "వ్యక్తిగత వివరాలు",
    travelDetails: "యాత్ర వివరాలు",
    reviewPay: "సమీక్ష మరియు చెల్లింపు",
    fullName: "పూర్తి పేరు",
    mobile: "మొబైల్ నంబర్",
    emailOpt: "ఇమెయిల్ (ఐచ్ఛికం)",
    address: "చిరునామా",
    age: "వయసు",
    fatherName: "తండ్రి / భర్త పేరు",
    gender: "లింగం",
    aadhar: "ఆధార్ నంబర్",
    vrat: "వ్రతం ఉంటారా?",
    vatHint: "యాత్రలో ఉపవాసం ఉంటారా?",
    noOfSeats: "సీట్ల సంఖ్య",
    boardingPoint: "ఎక్కే స్థలం",
    totalAmount: "మొత్తం మొత్తం",
    continueBtn: "కొనసాగించు",
    confirmPay: "నిర్ధారించి చెల్లించు",
    additionalPassengers: "అదనపు ప్రయాణికులు",
    passengerNum: "ప్రయాణికుడు",
    gallery: "గ్యాలరీ",
    photos: "ఫోటోలు",
    videos: "వీడియోలు",
    bhajans: "భజనలు",
    chalisa: "చాలీసా",
    aarti: "ఆరతి",
    dashboard: "డాష్‌బోర్డ్",
    users: "వినియోగదారులు",
    members: "సభ్యులు",
    enquiries: "విచారణలు",
    feedback: "అభిప్రాయం",
    donations: "దానాలు",
    settings: "సెట్టింగులు",
    noResults: "ఫలితాలు లేవు",
    tryAgain: "మళ్ళీ ప్రయత్నించు",
    contactUs: "మాతో సంప్రదించు",
    about: "మా గురించి",
    myBookingsSub: "మీ యాత్రలు",
    loginToViewBookings: "బుకింగులు చూడటానికి లాగిన్ చేయి",
    loginRegister: "లాగిన్ / నమోదు",
    noBookingYet: "ఇంకా బుకింగులు లేవు",
    sacredJourneyAwaits: "మీ పవిత్ర యాత్ర వేచి ఉంది",
    exploreYatras: "యాత్రలు చూడు",
    viewTicket: "టికెట్ చూడు",
    welcomeBack: "తిరిగి స్వాగతం",
    welcomeBackSub: "స్వాగతం, భక్తుడు",
    joinUs: "చేరు",
    joinUsSub: "శ్యామ్ పరివార్‌లో స్వాగతం",
    resetPwd: "పాస్‌వర్డ్ రీసెట్",
    resetPwdSub: "మీ ఇమెయిల్‌కు రీసెట్ లింక్ పంపుతాం",
    marriageAidSub: "వివాహ సహాయం",
    aartiSub: "రోజువారీ ఆరతి",
    chalisaSub: "ఖాటూ శ్యామ్ చాలీసా",
    donationSuccessTitle: "దానం విజయవంతం",
    donationSuccessMsg: "జయ శ్రీ శ్యామ్! మీ దానం స్వీకరించబడింది.",
    donateHeroSub: "ప్రతి సేవ, శ్యామ్ జీ అనుగ్రహంతో.",
    anonymousDonate: "అనామక దానం",
    gallerySub: "దర్శనం మరియు జ్ఞాపకాలు",
    aboutHeroSub: "ట్రిప్‌కార్ట్ పరివార్",
    aboutMissionDesc:
      "ట్రిప్‌కార్ట్ పరివార్ ఖాటూ శ్యామ్ జీ మరియు సమాజ సేవకు అంకితమైన ఆధ్యాత్మిక కుటుంబం. మేము నెలవారీ యాత్రలు, భక్తి కార్యక్రమాలు మరియు సామాజిక సేవలు నిర్వహిస్తాం.",
    membershipHeroSub: "కుటుంబంలో భాగమవ్వు",
    membershipSuccessSub:
      "మీ దరఖాస్తు విజయవంతంగా సమర్పించబడింది.\nమేము త్వరలో సంప్రదిస్తాం.",
    devotionHeaderSub: "భక్తి · సంగీతం · ఆరతి",
    bhajanChipSub: "భజనలు",
    aartiChipSub: "ఆరతి",
    chalisaChipSub: "చాలీసా",
    kirtanChipSub: "కీర్తన",
    feedbackNote: "జయ శ్రీ శ్యామ్ · మీ అభిప్రాయం మా సేవలను మెరుగుపరుస్తుంది",
  },
};

const LanguageContext = createContext({
  lang: "EN",
  t: STRINGS.EN,
  toggle: () => {},
  setLanguage: () => {},
});

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("EN");

  useEffect(() => {
    AsyncStorage.getItem(STORAGE_KEY)
      .then((saved) => {
        if (saved && STRINGS[saved]) setLang(saved);
      })
      .catch(() => {});
  }, []);

  const toggle = useCallback(() => {
    setLang((l) => {
      const next = l === "EN" ? "HI" : "EN";
      AsyncStorage.setItem(STORAGE_KEY, next).catch(() => {});
      return next;
    });
  }, []);

  const setLanguage = useCallback((code) => {
    const validCode = STRINGS[code] ? code : "EN";
    AsyncStorage.setItem(STORAGE_KEY, validCode).catch(() => {});
    setLang(validCode);
  }, []);

  return (
    <LanguageContext.Provider
      value={{ lang, t: STRINGS[lang] || STRINGS.EN, toggle, setLanguage }}
    >
      {children}
    </LanguageContext.Provider>
  );
}

export const useLang = () => useContext(LanguageContext);
